# -*- coding: utf-8 -*-
"""
/***************************************************************************
 flexgi_test
                                 A QGIS plugin
 This is a test plugin for flexigis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-16
        copyright            : (C) 2020 by chinonso
        email                : unaichi.chinonso@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load flexgi_test class from file flexgi_test.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flexgi_test import flexgi_test
    return flexgi_test(iface)
